export const countryCodes = {
  'Argentina': { code: 'ar', flag: '🇦🇷' },
  'Austria': { code: 'at', flag: '🇦🇹' },
  'Australia': { code: 'au', flag: '🇦🇺' },
  'Belgium': { code: 'be', flag: '🇧🇪' },
  'Brazil': { code: 'br', flag: '🇧🇷' },
  'Bulgaria': { code: 'bg', flag: '🇧🇬' },
  'China': { code: 'cn', flag: '🇨🇳' },
  'Canada': { code: 'ca', flag: '🇨🇦' },
  'Colombia': { code: 'co', flag: '🇨🇴' },
  'Cuba': { code: 'cu', flag: '🇨🇺' },
  'Czech Republic': { code: 'cz', flag: '🇨🇿' },
  'Egypt': { code: 'eg', flag: '🇪🇬' },
  'France': { code: 'fr', flag: '🇫🇷' },
  'Germany': { code: 'de', flag: '🇩🇪' },
  'Greece': { code: 'gr', flag: '🇬🇷' },
  'Hong Kong': { code: 'hk', flag: '🇭🇰' },
  'Hungary': { code: 'hu', flag: '🇭🇺' },
  'India': { code: 'in', flag: '🇮🇳' },
  'Indonesia': { code: 'id', flag: '🇮🇩' },
  'Ireland': { code: 'ie', flag: '🇮🇪' },
  'Israel': { code: 'il', flag: '🇮🇱' },
  'Italy': { code: 'it', flag: '🇮🇹' },
  'Japan': { code: 'jp', flag: '🇯🇵' },
  'Latvia': { code: 'lv', flag: '🇱🇻' },
  'Lithuania': { code: 'lt', flag: '🇱🇹' },
  'Malaysia': { code: 'my', flag: '🇲🇾' },
  'Mexico': { code: 'mx', flag: '🇲🇽' },
  'Morocco': { code: 'ma', flag: '🇲🇦' },
  'Netherlands': { code: 'nl', flag: '🇳🇱' },
  'New Zealand': { code: 'nz', flag: '🇳🇿' },
  'Nigeria': { code: 'ng', flag: '🇳🇬' },
  'Norway': { code: 'no', flag: '🇳🇴' },
  'Philippines': { code: 'ph', flag: '🇵🇭' },
  'Poland': { code: 'pl', flag: '🇵🇱' },
  'Portugal': { code: 'pt', flag: '🇵🇹' },
  'Romania': { code: 'ro', flag: '🇷🇴' },
  'Russia': { code: 'ru', flag: '🇷🇺' },
  'Saudi Arabia': { code: 'sa', flag: '🇸🇦' },
  'Serbia': { code: 'rs', flag: '🇷🇸' },
  'Singapore': { code: 'sg', flag: '🇸🇬' },
  'Slovakia': { code: 'sk', flag: '🇸🇰' },
  'Slovenia': { code: 'si', flag: '🇸🇮' },
  'South Africa': { code: 'za', flag: '🇿🇦' },
  'South Korea': { code: 'kr', flag: '🇰🇷' },
  'Sweden': { code: 'se', flag: '🇸🇪' },
  'Switzerland': { code: 'ch', flag: '🇨🇭' },
  'Taiwan': { code: 'tw', flag: '🇹🇼' },
  'Thailand': { code: 'th', flag: '🇹🇭' },
  'Turkey': { code: 'tr', flag: '🇹🇷' },
  'UAE': { code: 'ae', flag: '🇦🇪' },
  'Ukraine': { code: 'ua', flag: '🇺🇦' },
  'United Kingdom': { code: 'gb', flag: '🇬🇧' },
  'United States': { code: 'us', flag: '🇺🇸' },
  'Venezuela': { code: 've', flag: '🇻🇪' }
};


export default countryCodes
